name: spacecat_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - anndata
  - numpy
  - pandas
  - scipy
  - squidpy
  - pip:
    - alpineer==0.1.12
    - ark-analysis==0.7.1
    - .